/* CSS */
import "@/styles/globals.css";
import '@rainbow-me/rainbowkit/styles.css';

import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import React from "react";
import Providers from "@/app/providers";
import {RetroNavbar} from "@/components/retro-navbar";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
                                       children: React.ReactNode;
                                   }>
) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Providers>
                <RetroNavbar/>
                {children}
            </Providers>
        </body>
        </html>
    );
}